### ISSUE TITLE
Error messages each time selecting text/html part:

### ISSUE THREAD

**Issue by andruska** [ohwgiles/wemed#3]
I installed last version (0.5) from AUR
I use Wemed for email editing (adding MIME parts for notes) purposes in Claws mail actions (/usr/bin/wemed %F). 

Currently I get error messages (shown on action input/output log) each time selecting text/html part:

--- Ended: /usr/bin/wemed "/home/moca/Local Mail/inbox/Logins/30"
/usr/bin/xdg-mime: line 323: [: too many arguments
/usr/bin/xdg-mime: line 325: [: too many arguments
grep: /usr/share/applications/userapp-Pale Moon-NGQZWY.desktop: No such file or directory

**Comment by ohwgiles** [comment]
These errors are caused by wemed being unable to find the right external program for the "edit in external application" option. They are harmless, but I've been meaning to improve that mechanism anyway so I'll take a look at this

**Comment by ohwgiles** [comment]
Among other improvements, I've pushed a change that should correctly find the preferred mime app and fix the last error you mentioned. The two from `xdg-mime` I kind of looks like this bug: https://bugs.freedesktop.org/show_bug.cgi?id=101039 but I'm also on Arch Linux and I can't reproduce it

**Comment by andruska** [comment]
I can reproduce it even using Wemed alone from command line without Claws Mail. Sample email is attached to this message.
[5.txt](https://github.com/ohwgiles/wemed/files/1441351/5.txt)

Now just select text/html part

$ wemed
/usr/bin/xdg-mime: line 323: [: too many arguments
/usr/bin/xdg-mime: line 325: [: too many arguments
grep: /usr/share/applications/userapp-Pale Moon-NGQZWY.desktop: No such file or directory

I dont understand, why it needs at all external program when webkitgtk can handle all what related to displaying and editing html. There is no any need for external browser (in current situation this Pale Moon).
For second I'm not sure why it seaches for "/usr/share/applications/userapp-Pale Moon-NGQZWY.desktop". The correct one is "/usr/share/applications/palemoon.desktop" on my system. But in same time:

# xdg-settings get default-web-browser
firefox.desktop

**Comment by ohwgiles** [comment]
So, with commit 53fe36acbba5e3b746a7b702346468a21288afa6 I resolved the searching for the `.desktop` file in the correct location. This fixes the error from grep - please try with the latest code from master.

You are correct that for text and html parts, no external program is needed. However, for many cases (attachments), opening a part in an external program is really necessary. So for simplicity, wemed enables this feature for every part (from the Part menu).

Wemed calls `xdg-mime query default $MIMETYPE` to determine the preferred external application since this can work for all mime-types, html is not treated specially. I think the error from `xdg-mime` about too many arguments is unrelated to wemed, this is the specific thing I cannot reproduce and I suspect is connected specifically to your Pale Moon `.desktop` file

**Comment by andruska** [comment]
After last commit to AUR I can test it now. The grep error is gone. The other errors related to xdg-mime are still intact. But as you mentioned, seems that these are not caused by wemed.
Anyway, thanks for wemed !
